// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.uj2016.dominio;

import es.uca.iw.uj2016.dominio.EmpresaDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EmpresaDataOnDemand_Roo_Configurable {
    
    declare @type: EmpresaDataOnDemand: @Configurable;
    
}
