// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.uj2016.dominio;

import es.uca.iw.uj2016.dominio.Empresa;
import es.uca.iw.uj2016.dominio.EmpresaDataOnDemand;
import es.uca.iw.uj2016.dominio.Usuario;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect EmpresaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmpresaDataOnDemand: @Component;
    
    private Random EmpresaDataOnDemand.rnd = new SecureRandom();
    
    private List<Empresa> EmpresaDataOnDemand.data;
    
    public Empresa EmpresaDataOnDemand.getNewTransientEmpresa(int index) {
        Empresa obj = new Empresa();
        setActividadProfesional(obj, index);
        setCif(obj, index);
        setEmail(obj, index);
        setIdUsuario(obj, index);
        setNombre(obj, index);
        setNumeroEmpleados(obj, index);
        return obj;
    }
    
    public void EmpresaDataOnDemand.setActividadProfesional(Empresa obj, int index) {
        String actividadProfesional = "actividadProfesional_" + index;
        if (actividadProfesional.length() > 128) {
            actividadProfesional = actividadProfesional.substring(0, 128);
        }
        obj.setActividadProfesional(actividadProfesional);
    }
    
    public void EmpresaDataOnDemand.setCif(Empresa obj, int index) {
        String cif = "cif_" + index;
        if (cif.length() > 32) {
            cif = new Random().nextInt(10) + cif.substring(1, 32);
        }
        obj.setCif(cif);
    }
    
    public void EmpresaDataOnDemand.setEmail(Empresa obj, int index) {
        String email = "foo" + index + "@bar.com";
        if (email.length() > 64) {
            email = email.substring(0, 64);
        }
        obj.setEmail(email);
    }
    
    public void EmpresaDataOnDemand.setIdUsuario(Empresa obj, int index) {
        Usuario idUsuario = null;
        obj.setIdUsuario(idUsuario);
    }
    
    public void EmpresaDataOnDemand.setNombre(Empresa obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 64) {
            nombre = nombre.substring(0, 64);
        }
        obj.setNombre(nombre);
    }
    
    public void EmpresaDataOnDemand.setNumeroEmpleados(Empresa obj, int index) {
        Integer numeroEmpleados = new Integer(index);
        obj.setNumeroEmpleados(numeroEmpleados);
    }
    
    public Empresa EmpresaDataOnDemand.getSpecificEmpresa(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Empresa obj = data.get(index);
        Integer id = obj.getId();
        return Empresa.findEmpresa(id);
    }
    
    public Empresa EmpresaDataOnDemand.getRandomEmpresa() {
        init();
        Empresa obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Empresa.findEmpresa(id);
    }
    
    public boolean EmpresaDataOnDemand.modifyEmpresa(Empresa obj) {
        return false;
    }
    
    public void EmpresaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Empresa.findEmpresaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Empresa' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Empresa>();
        for (int i = 0; i < 10; i++) {
            Empresa obj = getNewTransientEmpresa(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
