// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.uj2016.dominio;

import es.uca.iw.uj2016.dominio.ExperienciaProfesional;
import es.uca.iw.uj2016.dominio.ExperienciaProfesionalDataOnDemand;
import es.uca.iw.uj2016.dominio.Perfil;
import es.uca.iw.uj2016.dominio.PuestoDeTrabajo;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ExperienciaProfesionalDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ExperienciaProfesionalDataOnDemand: @Component;
    
    private Random ExperienciaProfesionalDataOnDemand.rnd = new SecureRandom();
    
    private List<ExperienciaProfesional> ExperienciaProfesionalDataOnDemand.data;
    
    public ExperienciaProfesional ExperienciaProfesionalDataOnDemand.getNewTransientExperienciaProfesional(int index) {
        ExperienciaProfesional obj = new ExperienciaProfesional();
        setFechaFin(obj, index);
        setFechaInicio(obj, index);
        setIdPerfil(obj, index);
        setIdPuestoDeTrabajo(obj, index);
        setNombreEmpresa(obj, index);
        return obj;
    }
    
    public void ExperienciaProfesionalDataOnDemand.setFechaFin(ExperienciaProfesional obj, int index) {
        Date fechaFin = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaFin(fechaFin);
    }
    
    public void ExperienciaProfesionalDataOnDemand.setFechaInicio(ExperienciaProfesional obj, int index) {
        Date fechaInicio = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaInicio(fechaInicio);
    }
    
    public void ExperienciaProfesionalDataOnDemand.setIdPerfil(ExperienciaProfesional obj, int index) {
        Perfil idPerfil = null;
        obj.setIdPerfil(idPerfil);
    }
    
    public void ExperienciaProfesionalDataOnDemand.setIdPuestoDeTrabajo(ExperienciaProfesional obj, int index) {
        PuestoDeTrabajo idPuestoDeTrabajo = null;
        obj.setIdPuestoDeTrabajo(idPuestoDeTrabajo);
    }
    
    public void ExperienciaProfesionalDataOnDemand.setNombreEmpresa(ExperienciaProfesional obj, int index) {
        String nombreEmpresa = "nombreEmpresa_" + index;
        if (nombreEmpresa.length() > 128) {
            nombreEmpresa = nombreEmpresa.substring(0, 128);
        }
        obj.setNombreEmpresa(nombreEmpresa);
    }
    
    public ExperienciaProfesional ExperienciaProfesionalDataOnDemand.getSpecificExperienciaProfesional(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ExperienciaProfesional obj = data.get(index);
        Integer id = obj.getId();
        return ExperienciaProfesional.findExperienciaProfesional(id);
    }
    
    public ExperienciaProfesional ExperienciaProfesionalDataOnDemand.getRandomExperienciaProfesional() {
        init();
        ExperienciaProfesional obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return ExperienciaProfesional.findExperienciaProfesional(id);
    }
    
    public boolean ExperienciaProfesionalDataOnDemand.modifyExperienciaProfesional(ExperienciaProfesional obj) {
        return false;
    }
    
    public void ExperienciaProfesionalDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ExperienciaProfesional.findExperienciaProfesionalEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ExperienciaProfesional' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ExperienciaProfesional>();
        for (int i = 0; i < 10; i++) {
            ExperienciaProfesional obj = getNewTransientExperienciaProfesional(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
