// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.uj2016.dominio;

import es.uca.iw.uj2016.dominio.FormacionAcademica;
import es.uca.iw.uj2016.dominio.FormacionAcademicaDataOnDemand;
import es.uca.iw.uj2016.dominio.Perfil;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect FormacionAcademicaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FormacionAcademicaDataOnDemand: @Component;
    
    private Random FormacionAcademicaDataOnDemand.rnd = new SecureRandom();
    
    private List<FormacionAcademica> FormacionAcademicaDataOnDemand.data;
    
    public FormacionAcademica FormacionAcademicaDataOnDemand.getNewTransientFormacionAcademica(int index) {
        FormacionAcademica obj = new FormacionAcademica();
        setCurso(obj, index);
        setIdPerfil(obj, index);
        setIdioma(obj, index);
        return obj;
    }
    
    public void FormacionAcademicaDataOnDemand.setCurso(FormacionAcademica obj, int index) {
        String curso = "curso_" + index;
        obj.setCurso(curso);
    }
    
    public void FormacionAcademicaDataOnDemand.setIdPerfil(FormacionAcademica obj, int index) {
        Perfil idPerfil = null;
        obj.setIdPerfil(idPerfil);
    }
    
    public void FormacionAcademicaDataOnDemand.setIdioma(FormacionAcademica obj, int index) {
        String idioma = "idioma_" + index;
        obj.setIdioma(idioma);
    }
    
    public FormacionAcademica FormacionAcademicaDataOnDemand.getSpecificFormacionAcademica(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FormacionAcademica obj = data.get(index);
        Integer id = obj.getId();
        return FormacionAcademica.findFormacionAcademica(id);
    }
    
    public FormacionAcademica FormacionAcademicaDataOnDemand.getRandomFormacionAcademica() {
        init();
        FormacionAcademica obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return FormacionAcademica.findFormacionAcademica(id);
    }
    
    public boolean FormacionAcademicaDataOnDemand.modifyFormacionAcademica(FormacionAcademica obj) {
        return false;
    }
    
    public void FormacionAcademicaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = FormacionAcademica.findFormacionAcademicaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FormacionAcademica' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FormacionAcademica>();
        for (int i = 0; i < 10; i++) {
            FormacionAcademica obj = getNewTransientFormacionAcademica(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
