// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.uj2016.dominio;

import es.uca.iw.uj2016.dominio.OfertaTrabajoTitulos;
import es.uca.iw.uj2016.dominio.OfertaTrabajoTitulosDataOnDemand;
import es.uca.iw.uj2016.dominio.OfertaTrabajoTitulosIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OfertaTrabajoTitulosIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OfertaTrabajoTitulosIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OfertaTrabajoTitulosIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OfertaTrabajoTitulosIntegrationTest: @Transactional;
    
    @Autowired
    OfertaTrabajoTitulosDataOnDemand OfertaTrabajoTitulosIntegrationTest.dod;
    
    @Test
    public void OfertaTrabajoTitulosIntegrationTest.testCountOfertaTrabajoTituloses() {
        Assert.assertNotNull("Data on demand for 'OfertaTrabajoTitulos' failed to initialize correctly", dod.getRandomOfertaTrabajoTitulos());
        long count = OfertaTrabajoTitulos.countOfertaTrabajoTituloses();
        Assert.assertTrue("Counter for 'OfertaTrabajoTitulos' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OfertaTrabajoTitulosIntegrationTest.testFindOfertaTrabajoTitulos() {
        OfertaTrabajoTitulos obj = dod.getRandomOfertaTrabajoTitulos();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajoTitulos' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajoTitulos' failed to provide an identifier", id);
        obj = OfertaTrabajoTitulos.findOfertaTrabajoTitulos(id);
        Assert.assertNotNull("Find method for 'OfertaTrabajoTitulos' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'OfertaTrabajoTitulos' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OfertaTrabajoTitulosIntegrationTest.testFindAllOfertaTrabajoTituloses() {
        Assert.assertNotNull("Data on demand for 'OfertaTrabajoTitulos' failed to initialize correctly", dod.getRandomOfertaTrabajoTitulos());
        long count = OfertaTrabajoTitulos.countOfertaTrabajoTituloses();
        Assert.assertTrue("Too expensive to perform a find all test for 'OfertaTrabajoTitulos', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<OfertaTrabajoTitulos> result = OfertaTrabajoTitulos.findAllOfertaTrabajoTituloses();
        Assert.assertNotNull("Find all method for 'OfertaTrabajoTitulos' illegally returned null", result);
        Assert.assertTrue("Find all method for 'OfertaTrabajoTitulos' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OfertaTrabajoTitulosIntegrationTest.testFindOfertaTrabajoTitulosEntries() {
        Assert.assertNotNull("Data on demand for 'OfertaTrabajoTitulos' failed to initialize correctly", dod.getRandomOfertaTrabajoTitulos());
        long count = OfertaTrabajoTitulos.countOfertaTrabajoTituloses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<OfertaTrabajoTitulos> result = OfertaTrabajoTitulos.findOfertaTrabajoTitulosEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'OfertaTrabajoTitulos' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'OfertaTrabajoTitulos' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OfertaTrabajoTitulosIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'OfertaTrabajoTitulos' failed to initialize correctly", dod.getRandomOfertaTrabajoTitulos());
        OfertaTrabajoTitulos obj = dod.getNewTransientOfertaTrabajoTitulos(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'OfertaTrabajoTitulos' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'OfertaTrabajoTitulos' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'OfertaTrabajoTitulos' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OfertaTrabajoTitulosIntegrationTest.testRemove() {
        OfertaTrabajoTitulos obj = dod.getRandomOfertaTrabajoTitulos();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajoTitulos' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajoTitulos' failed to provide an identifier", id);
        obj = OfertaTrabajoTitulos.findOfertaTrabajoTitulos(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'OfertaTrabajoTitulos' with identifier '" + id + "'", OfertaTrabajoTitulos.findOfertaTrabajoTitulos(id));
    }
    
}
