// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.uj2016.dominio;

import es.uca.iw.uj2016.dominio.OfertaDeTrabajo;
import es.uca.iw.uj2016.dominio.OfertaDeTrabajoDataOnDemand;
import es.uca.iw.uj2016.dominio.OfertaDeTrabajoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OfertaDeTrabajoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OfertaDeTrabajoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OfertaDeTrabajoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OfertaDeTrabajoIntegrationTest: @Transactional;
    
    @Autowired
    OfertaDeTrabajoDataOnDemand OfertaDeTrabajoIntegrationTest.dod;
    
    @Test
    public void OfertaDeTrabajoIntegrationTest.testCountOfertaDeTrabajoes() {
        Assert.assertNotNull("Data on demand for 'OfertaDeTrabajo' failed to initialize correctly", dod.getRandomOfertaDeTrabajo());
        long count = OfertaDeTrabajo.countOfertaDeTrabajoes();
        Assert.assertTrue("Counter for 'OfertaDeTrabajo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OfertaDeTrabajoIntegrationTest.testFindOfertaDeTrabajo() {
        OfertaDeTrabajo obj = dod.getRandomOfertaDeTrabajo();
        Assert.assertNotNull("Data on demand for 'OfertaDeTrabajo' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OfertaDeTrabajo' failed to provide an identifier", id);
        obj = OfertaDeTrabajo.findOfertaDeTrabajo(id);
        Assert.assertNotNull("Find method for 'OfertaDeTrabajo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'OfertaDeTrabajo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OfertaDeTrabajoIntegrationTest.testFindAllOfertaDeTrabajoes() {
        Assert.assertNotNull("Data on demand for 'OfertaDeTrabajo' failed to initialize correctly", dod.getRandomOfertaDeTrabajo());
        long count = OfertaDeTrabajo.countOfertaDeTrabajoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'OfertaDeTrabajo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<OfertaDeTrabajo> result = OfertaDeTrabajo.findAllOfertaDeTrabajoes();
        Assert.assertNotNull("Find all method for 'OfertaDeTrabajo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'OfertaDeTrabajo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OfertaDeTrabajoIntegrationTest.testFindOfertaDeTrabajoEntries() {
        Assert.assertNotNull("Data on demand for 'OfertaDeTrabajo' failed to initialize correctly", dod.getRandomOfertaDeTrabajo());
        long count = OfertaDeTrabajo.countOfertaDeTrabajoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<OfertaDeTrabajo> result = OfertaDeTrabajo.findOfertaDeTrabajoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'OfertaDeTrabajo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'OfertaDeTrabajo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OfertaDeTrabajoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'OfertaDeTrabajo' failed to initialize correctly", dod.getRandomOfertaDeTrabajo());
        OfertaDeTrabajo obj = dod.getNewTransientOfertaDeTrabajo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'OfertaDeTrabajo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'OfertaDeTrabajo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'OfertaDeTrabajo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OfertaDeTrabajoIntegrationTest.testRemove() {
        OfertaDeTrabajo obj = dod.getRandomOfertaDeTrabajo();
        Assert.assertNotNull("Data on demand for 'OfertaDeTrabajo' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OfertaDeTrabajo' failed to provide an identifier", id);
        obj = OfertaDeTrabajo.findOfertaDeTrabajo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'OfertaDeTrabajo' with identifier '" + id + "'", OfertaDeTrabajo.findOfertaDeTrabajo(id));
    }
    
}
