// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.uj2016.dominio;

import es.uca.iw.uj2016.dominio.PuestoDeTrabajo;
import es.uca.iw.uj2016.dominio.PuestoDeTrabajoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PuestoDeTrabajoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PuestoDeTrabajoDataOnDemand: @Component;
    
    private Random PuestoDeTrabajoDataOnDemand.rnd = new SecureRandom();
    
    private List<PuestoDeTrabajo> PuestoDeTrabajoDataOnDemand.data;
    
    public PuestoDeTrabajo PuestoDeTrabajoDataOnDemand.getNewTransientPuestoDeTrabajo(int index) {
        PuestoDeTrabajo obj = new PuestoDeTrabajo();
        setNombre(obj, index);
        return obj;
    }
    
    public void PuestoDeTrabajoDataOnDemand.setNombre(PuestoDeTrabajo obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 64) {
            nombre = nombre.substring(0, 64);
        }
        obj.setNombre(nombre);
    }
    
    public PuestoDeTrabajo PuestoDeTrabajoDataOnDemand.getSpecificPuestoDeTrabajo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PuestoDeTrabajo obj = data.get(index);
        Integer id = obj.getId();
        return PuestoDeTrabajo.findPuestoDeTrabajo(id);
    }
    
    public PuestoDeTrabajo PuestoDeTrabajoDataOnDemand.getRandomPuestoDeTrabajo() {
        init();
        PuestoDeTrabajo obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return PuestoDeTrabajo.findPuestoDeTrabajo(id);
    }
    
    public boolean PuestoDeTrabajoDataOnDemand.modifyPuestoDeTrabajo(PuestoDeTrabajo obj) {
        return false;
    }
    
    public void PuestoDeTrabajoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PuestoDeTrabajo.findPuestoDeTrabajoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PuestoDeTrabajo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PuestoDeTrabajo>();
        for (int i = 0; i < 10; i++) {
            PuestoDeTrabajo obj = getNewTransientPuestoDeTrabajo(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
