// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.uj2016.dominio;

import es.uca.iw.uj2016.dominio.PuestoDeTrabajo;
import es.uca.iw.uj2016.dominio.PuestoDeTrabajoDataOnDemand;
import es.uca.iw.uj2016.dominio.PuestoDeTrabajoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PuestoDeTrabajoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PuestoDeTrabajoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PuestoDeTrabajoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PuestoDeTrabajoIntegrationTest: @Transactional;
    
    @Autowired
    PuestoDeTrabajoDataOnDemand PuestoDeTrabajoIntegrationTest.dod;
    
    @Test
    public void PuestoDeTrabajoIntegrationTest.testCountPuestoDeTrabajoes() {
        Assert.assertNotNull("Data on demand for 'PuestoDeTrabajo' failed to initialize correctly", dod.getRandomPuestoDeTrabajo());
        long count = PuestoDeTrabajo.countPuestoDeTrabajoes();
        Assert.assertTrue("Counter for 'PuestoDeTrabajo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PuestoDeTrabajoIntegrationTest.testFindPuestoDeTrabajo() {
        PuestoDeTrabajo obj = dod.getRandomPuestoDeTrabajo();
        Assert.assertNotNull("Data on demand for 'PuestoDeTrabajo' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PuestoDeTrabajo' failed to provide an identifier", id);
        obj = PuestoDeTrabajo.findPuestoDeTrabajo(id);
        Assert.assertNotNull("Find method for 'PuestoDeTrabajo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PuestoDeTrabajo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PuestoDeTrabajoIntegrationTest.testFindAllPuestoDeTrabajoes() {
        Assert.assertNotNull("Data on demand for 'PuestoDeTrabajo' failed to initialize correctly", dod.getRandomPuestoDeTrabajo());
        long count = PuestoDeTrabajo.countPuestoDeTrabajoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'PuestoDeTrabajo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PuestoDeTrabajo> result = PuestoDeTrabajo.findAllPuestoDeTrabajoes();
        Assert.assertNotNull("Find all method for 'PuestoDeTrabajo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PuestoDeTrabajo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PuestoDeTrabajoIntegrationTest.testFindPuestoDeTrabajoEntries() {
        Assert.assertNotNull("Data on demand for 'PuestoDeTrabajo' failed to initialize correctly", dod.getRandomPuestoDeTrabajo());
        long count = PuestoDeTrabajo.countPuestoDeTrabajoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PuestoDeTrabajo> result = PuestoDeTrabajo.findPuestoDeTrabajoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PuestoDeTrabajo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PuestoDeTrabajo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PuestoDeTrabajoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PuestoDeTrabajo' failed to initialize correctly", dod.getRandomPuestoDeTrabajo());
        PuestoDeTrabajo obj = dod.getNewTransientPuestoDeTrabajo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PuestoDeTrabajo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PuestoDeTrabajo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PuestoDeTrabajo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PuestoDeTrabajoIntegrationTest.testRemove() {
        PuestoDeTrabajo obj = dod.getRandomPuestoDeTrabajo();
        Assert.assertNotNull("Data on demand for 'PuestoDeTrabajo' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PuestoDeTrabajo' failed to provide an identifier", id);
        obj = PuestoDeTrabajo.findPuestoDeTrabajo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PuestoDeTrabajo' with identifier '" + id + "'", PuestoDeTrabajo.findPuestoDeTrabajo(id));
    }
    
}
