// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.uj2016.dominio;

import es.uca.iw.uj2016.dominio.RolUsuario;
import es.uca.iw.uj2016.dominio.RolUsuarioDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RolUsuarioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RolUsuarioDataOnDemand: @Component;
    
    private Random RolUsuarioDataOnDemand.rnd = new SecureRandom();
    
    private List<RolUsuario> RolUsuarioDataOnDemand.data;
    
    public RolUsuario RolUsuarioDataOnDemand.getNewTransientRolUsuario(int index) {
        RolUsuario obj = new RolUsuario();
        setNombre(obj, index);
        return obj;
    }
    
    public void RolUsuarioDataOnDemand.setNombre(RolUsuario obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 32) {
            nombre = nombre.substring(0, 32);
        }
        obj.setNombre(nombre);
    }
    
    public RolUsuario RolUsuarioDataOnDemand.getSpecificRolUsuario(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        RolUsuario obj = data.get(index);
        Integer id = obj.getId();
        return RolUsuario.findRolUsuario(id);
    }
    
    public RolUsuario RolUsuarioDataOnDemand.getRandomRolUsuario() {
        init();
        RolUsuario obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return RolUsuario.findRolUsuario(id);
    }
    
    public boolean RolUsuarioDataOnDemand.modifyRolUsuario(RolUsuario obj) {
        return false;
    }
    
    public void RolUsuarioDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = RolUsuario.findRolUsuarioEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'RolUsuario' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<RolUsuario>();
        for (int i = 0; i < 10; i++) {
            RolUsuario obj = getNewTransientRolUsuario(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
