// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.uj2016.dominio;

import es.uca.iw.uj2016.dominio.TitulosFormacion;
import es.uca.iw.uj2016.dominio.TitulosFormacionDataOnDemand;
import es.uca.iw.uj2016.dominio.TitulosFormacionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TitulosFormacionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TitulosFormacionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TitulosFormacionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TitulosFormacionIntegrationTest: @Transactional;
    
    @Autowired
    TitulosFormacionDataOnDemand TitulosFormacionIntegrationTest.dod;
    
    @Test
    public void TitulosFormacionIntegrationTest.testCountTitulosFormacions() {
        Assert.assertNotNull("Data on demand for 'TitulosFormacion' failed to initialize correctly", dod.getRandomTitulosFormacion());
        long count = TitulosFormacion.countTitulosFormacions();
        Assert.assertTrue("Counter for 'TitulosFormacion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TitulosFormacionIntegrationTest.testFindTitulosFormacion() {
        TitulosFormacion obj = dod.getRandomTitulosFormacion();
        Assert.assertNotNull("Data on demand for 'TitulosFormacion' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TitulosFormacion' failed to provide an identifier", id);
        obj = TitulosFormacion.findTitulosFormacion(id);
        Assert.assertNotNull("Find method for 'TitulosFormacion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TitulosFormacion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TitulosFormacionIntegrationTest.testFindAllTitulosFormacions() {
        Assert.assertNotNull("Data on demand for 'TitulosFormacion' failed to initialize correctly", dod.getRandomTitulosFormacion());
        long count = TitulosFormacion.countTitulosFormacions();
        Assert.assertTrue("Too expensive to perform a find all test for 'TitulosFormacion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TitulosFormacion> result = TitulosFormacion.findAllTitulosFormacions();
        Assert.assertNotNull("Find all method for 'TitulosFormacion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TitulosFormacion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TitulosFormacionIntegrationTest.testFindTitulosFormacionEntries() {
        Assert.assertNotNull("Data on demand for 'TitulosFormacion' failed to initialize correctly", dod.getRandomTitulosFormacion());
        long count = TitulosFormacion.countTitulosFormacions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TitulosFormacion> result = TitulosFormacion.findTitulosFormacionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TitulosFormacion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TitulosFormacion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TitulosFormacionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TitulosFormacion' failed to initialize correctly", dod.getRandomTitulosFormacion());
        TitulosFormacion obj = dod.getNewTransientTitulosFormacion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TitulosFormacion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TitulosFormacion' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'TitulosFormacion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TitulosFormacionIntegrationTest.testRemove() {
        TitulosFormacion obj = dod.getRandomTitulosFormacion();
        Assert.assertNotNull("Data on demand for 'TitulosFormacion' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TitulosFormacion' failed to provide an identifier", id);
        obj = TitulosFormacion.findTitulosFormacion(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TitulosFormacion' with identifier '" + id + "'", TitulosFormacion.findTitulosFormacion(id));
    }
    
}
