// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.uj2016.dominio;

import es.uca.iw.uj2016.dominio.TitulosAcademicos;
import es.uca.iw.uj2016.dominio.TitulosAcademicosDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TitulosAcademicosDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TitulosAcademicosDataOnDemand: @Component;
    
    private Random TitulosAcademicosDataOnDemand.rnd = new SecureRandom();
    
    private List<TitulosAcademicos> TitulosAcademicosDataOnDemand.data;
    
    public TitulosAcademicos TitulosAcademicosDataOnDemand.getNewTransientTitulosAcademicos(int index) {
        TitulosAcademicos obj = new TitulosAcademicos();
        setNombre(obj, index);
        return obj;
    }
    
    public void TitulosAcademicosDataOnDemand.setNombre(TitulosAcademicos obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 128) {
            nombre = nombre.substring(0, 128);
        }
        obj.setNombre(nombre);
    }
    
    public TitulosAcademicos TitulosAcademicosDataOnDemand.getSpecificTitulosAcademicos(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TitulosAcademicos obj = data.get(index);
        Integer id = obj.getId();
        return TitulosAcademicos.findTitulosAcademicos(id);
    }
    
    public TitulosAcademicos TitulosAcademicosDataOnDemand.getRandomTitulosAcademicos() {
        init();
        TitulosAcademicos obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return TitulosAcademicos.findTitulosAcademicos(id);
    }
    
    public boolean TitulosAcademicosDataOnDemand.modifyTitulosAcademicos(TitulosAcademicos obj) {
        return false;
    }
    
    public void TitulosAcademicosDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TitulosAcademicos.findTitulosAcademicosEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TitulosAcademicos' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TitulosAcademicos>();
        for (int i = 0; i < 10; i++) {
            TitulosAcademicos obj = getNewTransientTitulosAcademicos(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
