// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.hijoprodigo.uj.dominio;

import es.uca.hijoprodigo.uj.dominio.Localizaciones;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Localizaciones_Roo_Configurable {
    
    declare @type: Localizaciones: @Configurable;
    
}
